FROM debian:stable-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    # --force-confdef = (Force configuration defaults)
    # --force-confold = (Force keep old files during upgrades)
    # Together these two settings prevent any interactive prompts during package installation
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold" \
    curl \
    python3-gi \
    python3-click \
    gir1.2-gtk-4.0 \
    ca-certificates \
    # libpng-dev is a library for PNG image support, 
    # commonly required by Python packages that work with images (ie. Pillow)
    # libpng-dev \
    # libssl-dev is a library for OpenSSL, which is required by many Python packages:
    # libssl-dev \
    # build-essential is a package that includes the GCC compiler, make, and other tools
    # build-essential \
    # zlib1g-dev is a library for compression,
    # commonly required by Python packages that work with compression
    # zlib1g-dev && \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/.local/bin

# Install UV   - CHANGED DUE TO ISSUES. NO IDEA.
# RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Install UV  - DOWNLOADING BINARY DIRECTLY
RUN curl -L https://github.com/astral-sh/uv/releases/download/0.9.27/uv-x86_64-unknown-linux-gnu.tar.gz \
  | tar -xz -C "/root/.local/bin" && \
  mv /root/.local/bin/uv-x86_64-unknown-linux-gnu/* /root/.local/bin

# Add UV to PATH
ENV PATH="/root/.local/bin:$PATH"

# Container needs to create its own venv
ENV UV_PROJECT_ENVIRONMENT=.venv-agent

# Add container venv python to PATH
# ENV PATH="/workspace/.venv-agent/bin:$PATH"

# RUN uv python install 3.12
RUN /root/.local/bin/uv python install 3.12

# Just - this is so the agent can utilize the justfile
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "/root/.local/bin"

# OpenCode
RUN curl -fsSL https://opencode.ai/install | bash

# Add OpenCode to PATH
# ENV PATH="/root/.opencode/bin:$PATH"

RUN echo "umask 002" >> /etc/profile

RUN cat > /entrypoint.sh <<'EOF'
#!/bin/sh
umask 0002
exec "$@"
EOF

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# Use `just sandbox` to build and run