name: my-agent

services:
  agent-sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
      args:
        # Remember ths depends on user namespace mapping:
        OWNER_UID: ${OWNER_UID:-1000}
        OWNER_GID: ${OWNER_GID:-1000}
        OWNER_NAME: ${OWNER_NAME:-brent}
    command: ["/root/.opencode/bin/opencode"]
    # command: ["/bin/bash"]
    image: agent-sandbox:latest
    hostname: agent-sandbox
    container_name: agent-sandbox
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      TZ: America/Los_Angeles

# run with:
# `just sandbox`