name: agent

services:
  agent-sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    # Set read_only to false to give agent ability to install system packages
    read_only: true
    command: ["/root/.opencode/bin/opencode"]
    image: agent-sandbox:latest
    hostname: agent-sandbox
    container_name: agent-sandbox
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      TZ: America/Los_Angeles
    cap_drop:
      - ALL
    # add these when needed
    # cap_add:  
    #   - CHOWN
    #   - DAC_OVERRIDE
    #   - FOWNER
    #   - SETGID
    #   - SETUID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

# run with:
# `just sandbox`