FROM debian:stable-slim

# Create a non-root user for the agent
# docker-compose.yaml sets these values, default 1001:1001
ARG USER_ID
ARG GROUP_ID

RUN groupadd -g ${GROUP_ID} agent-1 && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash agent-1

RUN apt-get update && apt-get install -y --no-install-recommends \
    # --force-confdef = (Force configuration defaults)
    # --force-confold = (Force keep old files during upgrades)
    # Together these two settings prevent any interactive prompts during package installation
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold" \
    curl \
    python3-gi \
    python3-click \
    gir1.2-gtk-4.0 \
    ca-certificates \
    # libpng-dev is a library for PNG image support, 
    # commonly required by Python packages that work with images (ie. Pillow)
    # libpng-dev \
    # libssl-dev is a library for OpenSSL, which is required by many Python packages:
    # libssl-dev \
    # build-essential is a package that includes the GCC compiler, make, and other tools
    # build-essential \
    # zlib1g-dev is a library for compression,
    # commonly required by Python packages that work with compression
    # zlib1g-dev && \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER agent-1
WORKDIR /workspace

RUN mkdir -p /home/agent-1/.local/bin

# Install UV   - CHANGED DUE TO ISSUES. NO FUCKING IDEA.
# RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Install UV  - TEST DOWNLOADING BINARY DIRECTLY
RUN curl -L https://github.com/astral-sh/uv/releases/download/0.9.27/uv-x86_64-unknown-linux-gnu.tar.gz \
  | tar -xz -C "/home/agent-1/.local/bin" && \
  mv /home/agent-1/.local/bin/uv-x86_64-unknown-linux-gnu/* /home/agent-1/.local/bin

# Add UV to PATH
ENV PATH="/home/agent-1/.local/bin:$PATH"

# Container needs to create its own venv
ENV UV_PROJECT_ENVIRONMENT=.venv-agent

# Add container venv python to PATH
# ENV PATH="/workspace/.venv-agent/bin:$PATH"

# RUN uv python install 3.12
RUN /home/agent-1/.local/bin/uv python install 3.12

# Just - this is so the agent can utilize the justfile
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "$HOME/.local/bin"

# OpenCode
RUN curl -fsSL https://opencode.ai/install | bash

# Add OpenCode to PATH
ENV PATH="/home/agent-1/.opencode/bin:$PATH"


ENTRYPOINT ["tail", "-f", "/dev/null"]
# Use docker-compose.yaml to build